
// check examples/BearSSL_ServerClientCert/ for documentation on how to
// generate such certificates and keys for your own project.

#pragma message("DO NOT USE THE SAMPLE CERTS, KEYS, OR CAS IN YOUR OWN PROJECT!!!")

#if !USING_INSECURE_CERTS_AND_KEYS_AND_CAS
#error Certificates, keys and CAs which are not kept secretly are absolutely not safe to use
#endif

#ifndef USE_EC

#pragma message("SSL: Elliptic curve is NOT used in this example")

// The hardcoded certificate authority used in examples
// Don't use it on your own apps!!!!!
const char ca_cert[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIIC1TCCAb2gAwIBAgIJAMPt1Ms37+hLMA0GCSqGSIb3DQEBCwUAMCExCzAJBgNV
BAYTAlVTMRIwEAYDVQQDDAkxMjcuMC4wLjMwHhcNMTgwMzE0MDQyMTU0WhcNMjkw
NTMxMDQyMTU0WjAhMQswCQYDVQQGEwJVUzESMBAGA1UEAwwJMTI3LjAuMC4zMIIB
IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxsa4qU/tlzN4YTcnn/I/ffsi
jOPc8QRcwClKzasIZNFEye4uThl+LGZWFIFb8X8Dc+xmmBaWlPJbqtphgFKStpar
DdduHSW1ud6Y1FVKxljo3UwCMrYm76Q/jNzXJvGs6Z1MDNsVZzGJaoqit2H2Hkvk
y+7kk3YbEDlcyVsLOw0zCKL4cd2DSNDyhIZxWo2a8Qn5IdjWAYtsTnW6MvLk/ya4
abNeRfSZwi+r37rqi9CIs++NpL5ynqkKKEMrbeLactWgHbWrZeaMyLpuUEL2GF+w
MRaAwaj7ERwT5gFJRqYwj6bbfIdx5PC7h7ucbyp272MbrDa6WNBCMwQO222t4wID
AQABoxAwDjAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQCmXfrC42nW
IpL3JDkB8YlB2QUvD9JdMp98xxo33+xE69Gov0e6984F1Gluao0p6sS7KF+q3YLS
4hjnzuGzF9GJMimIB7NMQ20yXKfKpmKJ7YugMaKTDWDhHn5679mKVbLSQxHCUMEe
tEnMT93/UaDbWBjV6zu876q5vjPMYgDHODqO295ySaA71UkijaCn6UwKUT49286T
V9ZtzgabNGHXfklHgUPWoShyze+G3g29I1BR0qABoJI63zaNu8ua42v5g1RldxsW
X8yKI14mFOGxuvcygG8L2xxysW7Zq+9g+O7gW0Pm6RDYnUQmIwY83h1KFCtYCJdS
2PgozwkkUNyP
-----END CERTIFICATE-----
)EOF";

// The server's private key which must be kept secret
const char server_private_key[] PROGMEM = R"EOF(
-----BEGIN PRIVATE KEY-----
MIIEuwIBADANBgkqhkiG9w0BAQEFAASCBKUwggShAgEAAoIBAQCp6pq+ADShiRDE
YU5E+uQe2K0HWWy94dWq5wErW+nFT1p2ItggWlL3z0e5TOxMm1yqL6WenR8iA2qi
TTb7FjRIcblIwdI8JHo5K8xa0IHkQRaFkPMsFHk+dXIsJMVIOFnrUbtV/VMsSJLP
opZnMrn83d/rrtrr1BortPKNxzeoLRVpizs/GNLFFE30WL/J2Ov1WU/hTr3pHJmz
IfiPV7xpmt19/yGGg6kfZR1W8ws2sgonAv/FlixppqmZ7CsQDC/mrVky+/cTyu6F
G6jxdfQyTYGfKaWzBj9ikAJ9ghkLdZ9jc4mIkW7J+hXtrI6UXOeSXtiv8lR4jBVP
fHsSLdWfAgMBAAECggEAR2SwNRIgCxlsxp6+BMTIMd/Hv/VGd/gaT281chLyA/oG
H+ofFmTtRHs+/zA/fyauRkGz3JPXH3MBDIXWCqT3PdMuz0/E9ok7I6dv+15tnUrt
3Bwd2JEXqnMtkDe4/tHSkknqpURF/K7XpM+DU4QgWoudSMlU6c7aWi/y1Dh2/b2X
FgxrHg+k8dst7JXWewODxeMJu+gbhGn9e3iZyhcvb48kvpxBa9YJz17lV5fVhLLH
CBkzWL7t+j7yRHB5gxwOkRfIxilPxoC4vGYYgVx7akhDS/SdRIirtNGQjOgeZrhd
GchwrONK2253qbMtZ/BpuVHpkYxc7H6+hF5oM1yLLQKBgQC4nf2UoerdEhoDD7aT
CdGsj6f2mBnJBWyZ2wHFYbryOaVYULzFUa1K3iZaH63O3qRs6W1YI3O4HLjIW4Gh
3yAutjqPQP9WLSqrJzsVnoqIgsgBO0e82dWgbz4pYbaib/NDrnbypqCcaYm27Yq1
WvUrCUaMW1cGUDkJ0H+iwAHnvQKBgQDrnXzlhBgum/QBXgX9H82xhTqmwGzb0g0u
g6jMn7nFrRe0yanCI8hpkxLBIP5perkAmcrRnQJvKGOYX05JxcRTEHk99b3ui1+w
ullU9jGlTyBgGIrbe6H0ktqmp8Y+tlUgZaEU8+lgoP4ZZOkWEzYRKpU3CpKXAOeU
OOoDh6AqiwKBgQCXbiAd1mJLSxnDARSErz0pCfx/rGsaFDTsTlO5j1xEazxQoIj2
YPR/wJA8xFdQpBbCrwVdklbM4eI/la9TEy3WouqNrobCLPIeyWMRbKW9K2jaecFy
CkvL+PNIBjpEKweisGwoxLxhD8BCJ73q29zVnBod7p4HM65Veov29v+ZEQJ/TGPD
Gqa5MGNfuRHC305wYh3P5kB9CsgPfgUxtSYUFQMJrJO1djwjvhbw/ay0z336fTdf
ipZdM6zknYJI36I/BK9Sn8QM0Epfu+yvCdzIO9BrrrxGSOLMn379ZQsAO1TiRJ6u
mxx5jdqkh5cv+vg/j1E/D5ld7ZddfbD2Li7KvwKBgEn065T/57IffzOdXsSXYHeH
PK+z1fvSZ9U7vK7asmzpMdqx8WjJN9Te02Hz45jptbAIbHM/TkSYfp4ENyu+HEI5
OJATsq82xS1xa9GeDd+f1jtfAHgMKpokHlCI/REbSVwkE8ydnfTTa/Fbigp6dqxv
k3PJ8ZBWXVG0dpBTKH47
-----END PRIVATE KEY-----

)EOF";

// The server's public certificate which must be shared
const char server_cert[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIIDnzCCAocCFGJk9Z+xTdd4gO1+XUSXcU1rk0GvMA0GCSqGSIb3DQEBCwUAMIGL
MQswCQYDVQQGEwJQVDERMA8GA1UECAwIUG9ydHVnYWwxETAPBgNVBAcMCFBvcnR1
Z2FsMQwwCgYDVQQKDANJUEwxDDAKBgNVBAsMA0lQTDERMA8GA1UEAwwIY2FyZWxp
bmUxJzAlBgkqhkiG9w0BCQEWGGNhcmVsaW5lMTgxOTIwQGdtYWlsLmNvbTAeFw0y
NDAxMTUwMjQ0NDdaFw0yNDAyMTQwMjQ0NDdaMIGLMQswCQYDVQQGEwJQVDERMA8G
A1UECAwIUG9ydHVnYWwxETAPBgNVBAcMCFBvcnR1Z2FsMQwwCgYDVQQKDANJUEwx
DDAKBgNVBAsMA0lQTDERMA8GA1UEAwwIY2FyZWxpbmUxJzAlBgkqhkiG9w0BCQEW
GGNhcmVsaW5lMTgxOTIwQGdtYWlsLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEP
ADCCAQoCggEBAKnqmr4ANKGJEMRhTkT65B7YrQdZbL3h1arnAStb6cVPWnYi2CBa
UvfPR7lM7EybXKovpZ6dHyIDaqJNNvsWNEhxuUjB0jwkejkrzFrQgeRBFoWQ8ywU
eT51ciwkxUg4WetRu1X9UyxIks+ilmcyufzd3+uu2uvUGiu08o3HN6gtFWmLOz8Y
0sUUTfRYv8nY6/VZT+FOvekcmbMh+I9XvGma3X3/IYaDqR9lHVbzCzayCicC/8WW
LGmmqZnsKxAML+atWTL79xPK7oUbqPF19DJNgZ8ppbMGP2KQAn2CGQt1n2NziYiR
bsn6Fe2sjpRc55Je2K/yVHiMFU98exIt1Z8CAwEAATANBgkqhkiG9w0BAQsFAAOC
AQEAJ0ngZ5OWG5R4ylkAWt/1dJ03D0h5opNTkkkJuWnKHNhR7zsug0Sa8asF73gx
c2nO2EOwj7XbnJlNAwCsc9oB+HkLz6OTWaEYx5UXkV9JDGGAio3i1KNrfsoYcX06
oTeX5PCn74DsRPmD0myBfnA8KN/CBhKWQASwxomY4lE92LnN/iMTTBXN3oU8zqU1
jdxRlv3294/EntskSji+OkeyZeKkXfTFfN6Y0uWHSmlGnC4S+njF9eNkfCqtBX84
xA9VYsQjFkTNHz2guNrLr39xSTklob/Jq4LmXEuUWJia6jXLWNJqzfdfrvZzvA8C
bxN7NKwHvzer9V2d4G/z03SZ7g==
-----END CERTIFICATE-----
)EOF";

#else // USE_EC is defined

#pragma message("SSL: Elliptic curve IS used in this example")

const char server_cert[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIIDnzCCAocCFGJk9Z+xTdd4gO1+XUSXcU1rk0GvMA0GCSqGSIb3DQEBCwUAMIGL
MQswCQYDVQQGEwJQVDERMA8GA1UECAwIUG9ydHVnYWwxETAPBgNVBAcMCFBvcnR1
Z2FsMQwwCgYDVQQKDANJUEwxDDAKBgNVBAsMA0lQTDERMA8GA1UEAwwIY2FyZWxp
bmUxJzAlBgkqhkiG9w0BCQEWGGNhcmVsaW5lMTgxOTIwQGdtYWlsLmNvbTAeFw0y
NDAxMTUwMjQ0NDdaFw0yNDAyMTQwMjQ0NDdaMIGLMQswCQYDVQQGEwJQVDERMA8G
A1UECAwIUG9ydHVnYWwxETAPBgNVBAcMCFBvcnR1Z2FsMQwwCgYDVQQKDANJUEwx
DDAKBgNVBAsMA0lQTDERMA8GA1UEAwwIY2FyZWxpbmUxJzAlBgkqhkiG9w0BCQEW
GGNhcmVsaW5lMTgxOTIwQGdtYWlsLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEP
ADCCAQoCggEBAKnqmr4ANKGJEMRhTkT65B7YrQdZbL3h1arnAStb6cVPWnYi2CBa
UvfPR7lM7EybXKovpZ6dHyIDaqJNNvsWNEhxuUjB0jwkejkrzFrQgeRBFoWQ8ywU
eT51ciwkxUg4WetRu1X9UyxIks+ilmcyufzd3+uu2uvUGiu08o3HN6gtFWmLOz8Y
0sUUTfRYv8nY6/VZT+FOvekcmbMh+I9XvGma3X3/IYaDqR9lHVbzCzayCicC/8WW
LGmmqZnsKxAML+atWTL79xPK7oUbqPF19DJNgZ8ppbMGP2KQAn2CGQt1n2NziYiR
bsn6Fe2sjpRc55Je2K/yVHiMFU98exIt1Z8CAwEAATANBgkqhkiG9w0BAQsFAAOC
AQEAJ0ngZ5OWG5R4ylkAWt/1dJ03D0h5opNTkkkJuWnKHNhR7zsug0Sa8asF73gx
c2nO2EOwj7XbnJlNAwCsc9oB+HkLz6OTWaEYx5UXkV9JDGGAio3i1KNrfsoYcX06
oTeX5PCn74DsRPmD0myBfnA8KN/CBhKWQASwxomY4lE92LnN/iMTTBXN3oU8zqU1
jdxRlv3294/EntskSji+OkeyZeKkXfTFfN6Y0uWHSmlGnC4S+njF9eNkfCqtBX84
xA9VYsQjFkTNHz2guNrLr39xSTklob/Jq4LmXEuUWJia6jXLWNJqzfdfrvZzvA8C
bxN7NKwHvzer9V2d4G/z03SZ7g==
-----END CERTIFICATE-----
)EOF";

// The server's private key which must be kept secret
const char server_private_key[] PROGMEM = R"EOF(
-----BEGIN EC PARAMETERS-----
BggqhkjOPQMBBw==
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIKyLR9/NT7ZdWM+2rklehveuk+jyIHJ+P8ZUQ392HOYvoAoGCCqGSM49
AwEHoUQDQgAExIkZw7zjk6TGcScff1PAehuEGmKZTf8VfnkjyJH0IbBgZibZ+qwY
GBEnkz4KpKv7TkHoW+j7F5EMcLcSrUIpyw==
-----END EC PRIVATE KEY-----
)EOF";

#endif // USE_EC is defined
